name: Translate Content

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  translate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Translate Main Content Files
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar"
        input_file_path: "README.md"
        output_file_name_prefix: "README."
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
        
    - name: Translate Homepage Content
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar"
        input_file_path: "01 BY MB Consultancy - Home Page Content.md"
        output_file_name_prefix: "translations/01 BY MB Consultancy - Home Page Content."
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
        
    - name: Translate About Us Content
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar"
        input_file_path: "02 About Us Page Content.md"
        output_file_name_prefix: "translations/02 About Us Page Content."
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

    - name: Translate Solution Page Content
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar"
        input_file_path: "03 Solution Page Content.md"
        output_file_name_prefix: "translations/03 Solution Page Content."
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

    - name: Translate Online Store Page Content
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar"
        input_file_path: "04 Online Store Page Content.md"
        output_file_name_prefix: "translations/04 Online Store Page Content."
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

    - name: Translate What Makes Us Unique Page
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar"
        input_file_path: "05 What Makes Us Unique Page.md"
        output_file_name_prefix: "translations/05 What Makes Us Unique Page."
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

    - name: Translate Why Choose Us Page
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar"
        input_file_path: "06 Why Choose Us Page.md"
        output_file_name_prefix: "translations/06 Why Choose Us Page."
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

    - name: Translate Contact Us Page Content
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar"
        input_file_path: "07 Contact Us Page Content.md"
        output_file_name_prefix: "translations/07 Contact Us Page Content."
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

    - name: Translate Terms
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar"
        input_file_path: "08 Terms.md"
        output_file_name_prefix: "translations/08 Terms."
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

    - name: Translate Privacy Policies
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar"
        input_file_path: "09 Privacy Policie.md"
        output_file_name_prefix: "translations/09 Privacy Policie."
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

    - name: Translate Design Guidance
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar"
        input_file_path: "i. Design Guidance.md"
        output_file_name_prefix: "translations/i. Design Guidance."
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

    - name: Translate Customer Journey Analysis
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar"
        input_file_path: "ii. Customer Journey Analysis.md"
        output_file_name_prefix: "translations/ii. Customer Journey Analysis."
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

    - name: Translate General Information
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar"
        input_file_path: "iii. General Information.md"
        output_file_name_prefix: "translations/iii. General Information."
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
