name: Translate Content to Arabic

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly grant write permissions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create translations directory
        run: mkdir -p translations

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Test DeepL API connection
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST "https://api-free.deepl.com/v2/translate" \
            -H "Authorization: DeepL-Auth-Key ${{ secrets.DEEPL_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"text":["test"],"target_lang":"AR"}')
          if [ "$response" -ne 200 ]; then
            echo "DeepL API test failed with HTTP status $response"
            exit 1
          else
            echo "DeepL API connection successful"
          fi

      - name: Translate 00 intro.md
        uses: lyqht/deepl-translate-github-action@v2
        with:
          target_languages: "ar"
          input_file_path: "00 intro.md"
          output_file_name_prefix: "translations/00 intro"
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

      - name: Translate 08 Terms.md
        uses: lyqht/deepl-translate-github-action@v2
        with:
          target_languages: "ar"
          input_file_path: "08 Terms.md"
          output_file_name_prefix: "translations/08 Terms"
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

      - name: Translate Homepage (success-is-Jurney)
        uses: lyqht/deepl-translate-github-action@v2
        with:
          target_languages: "ar"
          input_file_path: "01A-Homepage -success-is-Jurney.md"
          output_file_name_prefix: "translations/01A-Homepage -success-is-Jurney"
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

      - name: Translate Homepage Content
        uses: lyqht/deepl-translate-github-action@v2
        with:
          target_languages: "ar"
          input_file_path: "01 BY MB Consultancy - Home Page Content.md"
          output_file_name_prefix: "translations/01 BY MB Consultancy - Home Page Content"
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

      - name: Translate Design Guidance
        uses: lyqht/deepl-translate-github-action@v2
        with:
          target_languages: "ar"
          input_file_path: "i. Design Guidance.md"
          output_file_name_prefix: "translations/i. Design Guidance"
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

      - name: Translate About Us Content
        uses: lyqht/deepl-translate-github-action@v2
        with:
          target_languages: "ar"
          input_file_path: "02 About Us Page Content.md"
          output_file_name_prefix: "translations/02 About Us Page Content"
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

      - name: Translate Solution Page Content
        uses: lyqht/deepl-translate-github-action@v2
        with:
          target_languages: "ar"
          input_file_path: "03 Solution Page Content.md"
          output_file_name_prefix: "translations/03 Solution Page Content"
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

      - name: Translate Contact Us Page Content
        uses: lyqht/deepl-translate-github-action@v2
        with:
          target_languages: "ar"
          input_file_path: "07 Contact Us Page Content.md"
          output_file_name_prefix: "translations/07 Contact Us Page Content"
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

      - name: Translate Why Choose Us Page
        uses: lyqht/deepl-translate-github-action@v2
        with:
          target_languages: "ar"
          input_file_path: "06 Why Choose Us Page.md"
          output_file_name_prefix: "translations/06 Why Choose Us Page"
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

      - name: Commit translations
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add Arabic translations for content files"
          file_pattern: "translations/*.ar.md"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
