name: Translate Content

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  translate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Translate Main Content Files
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar,fr"
        input_file_path: "README.md"
        output_file_name_pattern: "README.{language}.md"
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
        
    - name: Translate Homepage Content
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar,fr"
        input_file_path: "01 BY MB Consultancy - Home Page Content.md"
        output_file_name_pattern: "translations/01 BY MB Consultancy - Home Page Content.{language}.md"
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
        
    - name: Translate About Us Content
      uses: lyqht/deepl-translate-github-action@v2
      with:
        target_languages: "ar,fr"
        input_file_path: "02 About Us Page Content.md"
        output_file_name_pattern: "translations/02 About Us Page Content.{language}.md"
        deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
