name: Translate Files to Arabic

on:
  workflow_dispatch:
    inputs:
      files_to_translate:
        description: 'Comma-separated list of files to translate (leave empty to translate all root .md files)'
        required: false
        type: string
  push:
    paths:
      - "*.md"

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get list of files to translate
        id: get-files
        run: |
          if [ -n "${{ github.event.inputs.files_to_translate }}" ]; then
            # Use manually specified files
            echo "files=${{ github.event.inputs.files_to_translate }}" >> $GITHUB_OUTPUT
          else
            # Get all .md files in root directory
            files=$(find . -maxdepth 1 -name "*.md" -type f | sed 's|^\./||' | tr '\n' ',' | sed 's/,$//')
            echo "files=$files" >> $GITHUB_OUTPUT
          fi
          
      - name: Display files to translate
        run: |
          echo "Files to translate: ${{ steps.get-files.outputs.files }}"

      - name: Translate files
        uses: lyqht/deepl-translate-github-action@main
        with:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
          INPUT_FILE_PATH: ${{ steps.get-files.outputs.files }}
          OUTPUT_FILE_NAME_PATTERN: '{name}.ar.{ext}'
          TARGET_LANGUAGES: 'ar'

      - name: Check for changes
        id: check-changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: translations/arabic-${{ github.run_number }}
          title: "🌍 Add Arabic translations"
          commit-message: "feat: add Arabic translations for markdown files"
          body: |
            ## Arabic Translations
            
            This PR adds Arabic translations generated using DeepL API.
            
            ### Files Translated
            - Generated from workflow run #${{ github.run_number }}
            
            ### Notes
            - All translations are generated automatically using DeepL
            - Please review the translations before merging
            
            ---
            *This PR was created automatically by GitHub Actions*
          labels: |
            translation
            arabic
            automated
          reviewers: bader1919
